services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src/static:/app/src/static:rw
    restart: unless-stopped
    command: >
      python -m src.bot.main

  migrate:
    build: .
    command: alembic upgrade head

  redis:
    image: redis:7-alpine
    container_name: bot-redis
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

